---
- name: Install MariaDB
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: present

- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Allow external connections
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MariaDB

- name: Create the wiki database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create the wiki user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
