---
- name: Prepare all hosts
  hosts: mediawiki
  become: yes
  roles:
    - common

- name: Deploy MariaDB
  hosts: db
  become: yes
  roles:
    - mariadb

- name: Deploy Apache, PHP and MediaWiki
  hosts: web
  become: yes
  roles:
    - apache_php
    - mediawiki
